/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.devteam.school.views;

import com.devteam.school.app.AppContext;

/**
 *
 * @author alexh
 */
public class AppFrame extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public AppFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbProfesorLauncher = new javax.swing.JButton();
        jbAlumnoLaucher = new javax.swing.JButton();
        jbCorsoLaucher = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbProfesorLauncher.setText("Profesores");
        jbProfesorLauncher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbProfesorLauncherMouseReleased(evt);
            }
        });

        jbAlumnoLaucher.setText("Alumnos");
        jbAlumnoLaucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbAlumnoLaucherMouseReleased(evt);
            }
        });

        jbCorsoLaucher.setText("Cursos");
        jbCorsoLaucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbCorsoLaucherMouseReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Droid Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pedrito High School");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jbProfesorLauncher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAlumnoLaucher)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCorsoLaucher)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbProfesorLauncher)
                    .addComponent(jbAlumnoLaucher)
                    .addComponent(jbCorsoLaucher))
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbProfesorLauncherMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbProfesorLauncherMouseReleased
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProfesorFrame form = ProfesorFrame.getInstance();
                form.setVisible(true);
                form.toFront();
            }
        });
    }//GEN-LAST:event_jbProfesorLauncherMouseReleased

    private void jbAlumnoLaucherMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAlumnoLaucherMouseReleased
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlumnoFrame form = AlumnoFrame.getInstance();
                form.setVisible(true);
                form.toFront();
            }
        });
    }//GEN-LAST:event_jbAlumnoLaucherMouseReleased

    private void jbCorsoLaucherMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCorsoLaucherMouseReleased
        // TODO add your handling code here:
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CursoFrame form = CursoFrame.getInstance();
                form.setVisible(true);
                form.toFront();
            }
        });
    }//GEN-LAST:event_jbCorsoLaucherMouseReleased

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbAlumnoLaucher;
    private javax.swing.JButton jbCorsoLaucher;
    private javax.swing.JButton jbProfesorLauncher;
    // End of variables declaration//GEN-END:variables
}
