package com.devteam.school.views;

import com.devteam.school.app.AppContext;
import com.devteam.school.app.TableModelSchool;
import com.devteam.school.controllers.CursoController;
import com.devteam.school.controllers.ProfesorController;
import com.devteam.school.model.entities.Curso;
import com.devteam.school.model.entities.Profesor;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;


public class CursoChooserDialog extends javax.swing.JDialog {
    
    private final CursoController cursoController;
    private final ProfesorController profesorController;
    private List<Curso> cursos;
    
    TransferData transferData;

    /**
     * Creates new form CursoChooserDialog
     * @param parent
     * @param modal
     */
    public CursoChooserDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        cursoController = (CursoController) AppContext.getAppContext().getBean("cursoController");
        profesorController = (ProfesorController) AppContext.getAppContext().getBean("profesorController");
        
        cursos = cursoController.getCursos();
        fillTable( cursos );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtCursos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jtfTextoBuscar = new javax.swing.JTextField();
        jbBuscar = new javax.swing.JButton();
        jbActualizarTabla = new javax.swing.JButton();
        jlTotalRegistros = new javax.swing.JLabel();
        jlTitulo = new javax.swing.JLabel();
        jbAcceptDialog = new javax.swing.JButton();
        jbCancelDialog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jtCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCursosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtCursos);

        jLabel9.setText("Buscar");

        jtfTextoBuscar.setToolTipText("Nombre");
        jtfTextoBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfTextoBuscarKeyReleased(evt);
            }
        });

        jbBuscar.setBackground(new java.awt.Color(51, 51, 51));
        jbBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/google_custom_search.png"))); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbActualizarTabla.setBackground(new java.awt.Color(51, 51, 51));
        jbActualizarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        jbActualizarTabla.setText("Actualizar");
        jbActualizarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarTablaActionPerformed(evt);
            }
        });

        jlTotalRegistros.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlTotalRegistros.setText("Registros");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jtfTextoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jbActualizarTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlTotalRegistros, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbActualizarTabla)
                    .addComponent(jbBuscar)
                    .addComponent(jtfTextoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jlTotalRegistros)
                .addContainerGap())
        );

        jlTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("CURSOS REGISTRADOS");
        jlTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jbAcceptDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accept.png"))); // NOI18N
        jbAcceptDialog.setText("Elegir");
        jbAcceptDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbAcceptDialogMouseReleased(evt);
            }
        });

        jbCancelDialog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel.png"))); // NOI18N
        jbCancelDialog.setText("Cancelar");
        jbCancelDialog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jbCancelDialogMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCancelDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbAcceptDialog, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbAcceptDialog)
                    .addComponent(jbCancelDialog))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setTransfer(TransferData transferData){
        this.transferData = transferData;
    }
    
    private void jtCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCursosMouseClicked
        // TODO add your handling code here:
        
        if(evt.getClickCount() == 2){
            int indexRowSelected = jtCursos.rowAtPoint(evt.getPoint());
            transferData.transfer(cursos.get(indexRowSelected));
            dispose();
        }
       
    }//GEN-LAST:event_jtCursosMouseClicked

    private void jtfTextoBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTextoBuscarKeyReleased
        // TODO add your handling code here:
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            search();
        }

    }//GEN-LAST:event_jtfTextoBuscarKeyReleased

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed
        // TODO add your handling code here:
        search();

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbActualizarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarTablaActionPerformed
        // TODO add your handling code here:
        search();
    }//GEN-LAST:event_jbActualizarTablaActionPerformed

    private void jbCancelDialogMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbCancelDialogMouseReleased
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbCancelDialogMouseReleased

    private void jbAcceptDialogMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbAcceptDialogMouseReleased
        // TODO add your handling code here:
        int indexRowSelected = jtCursos.getSelectedRow();
        transferData.transfer(cursos.get(indexRowSelected));
        dispose();
        
    }//GEN-LAST:event_jbAcceptDialogMouseReleased

    private void search(){
        String searchText = jtfTextoBuscar.getText();
        cursos = cursoController.searchCursos(searchText);
        fillTable(cursos);
    }
    
    private void fillTable(List<Curso> cursos){
        String[] titles = {"ID", "Nombre", "Descripción", "Profesor"};
        DefaultTableModel model = new TableModelSchool(null, titles);

        String[] row = new String[4];

        Profesor profesor;
                
        for (Curso curso : cursos){
            row[0] = String.valueOf( curso.getId() );
            row[1] = curso.getNombre();
            row[2] = curso.getDescripcion();
            profesor = profesorController.getProfesorById(curso.getProfesorId());
            row[3] = profesor.getNombre() + " " + profesor.getApellidos();

            model.addRow(row);
        }

        jtCursos.setModel(model);
        jlTotalRegistros.setText( cursos.size() + " cursos");
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbAcceptDialog;
    private javax.swing.JButton jbActualizarTabla;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbCancelDialog;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JLabel jlTotalRegistros;
    private javax.swing.JTable jtCursos;
    private javax.swing.JTextField jtfTextoBuscar;
    // End of variables declaration//GEN-END:variables

    
}
